# Generated by Django 5.0.6 on 2024-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
