# Generated by Django 5.0.6 on 2024-06-09 08:58

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_useranswer_is_correct_answeroption_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
